$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$repositoryFullName = "theneutral0ne/true-aim"
$branchName = "main"
$bundleRelativePath = "dist/true-aim.bundle.lua"
$segmentPaths = @(
    "src/shared/00_bootstrap.lua",
    "src/games/00_registry.lua",
    "src/shared/05_runtime_state.lua",
    "src/games/bloodzone/00_settings.lua",
    "src/shared/10_core.lua",
    "src/games/bloodzone/10_ballistics.lua",
    "src/games/bloodzone/20_shield_mode.lua",
    "src/shared/20_ui.lua",
    "src/shared/30_visibility_targeting.lua",
    "src/shared/40_runtime.lua"
)

function Add-BundleLine {
    param(
        [System.Text.StringBuilder]$Builder,
        [string]$Line = ""
    )

    [void]$Builder.AppendLine($Line)
}

function ConvertTo-LuaQuotedStringLiteral {
    param([AllowNull()][string]$Text)

    if ($null -eq $Text) {
        return "nil"
    }

    $escapedText = $Text.Replace('\', '\\').Replace('"', '\"').Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $escapedText + '"'
}

function ConvertTo-LuaLongStringLiteral {
    param([AllowNull()][string]$Text)

    if ($null -eq $Text) {
        $Text = ""
    }

    $equalsCount = 0
    while ($true) {
        $delimiterEquals = '=' * $equalsCount
        $closingDelimiter = ']' + $delimiterEquals + ']'
        if ($Text.IndexOf($closingDelimiter, [System.StringComparison]::Ordinal) -lt 0) {
            return '[' + $delimiterEquals + '[' + $Text + ']' + $delimiterEquals + ']'
        }
        $equalsCount++
    }
}

function Get-TopLevelLocalExportNames {
    param([AllowNull()][string]$SourceText)

    $exportNameList = New-Object 'System.Collections.Generic.List[string]'
    if ($null -eq $SourceText) {
        return @()
    }

    $sourceLines = $SourceText -split "`r?`n"
    foreach ($sourceLine in $sourceLines) {
        if ($sourceLine -notmatch '^local\s+') {
            continue
        }

        if ($sourceLine -match '^local\s+function\s+([A-Za-z_][A-Za-z0-9_]*)') {
            $exportName = $Matches[1]
            if (-not $exportNameList.Contains($exportName)) {
                $exportNameList.Add($exportName) | Out-Null
            }
            continue
        }

        if ($sourceLine -match '^local\s+(.+?)\s*(?:=\s*.*)?$') {
            $declarationText = $Matches[1]
            foreach ($declarationPart in $declarationText -split ',') {
                $exportName = ($declarationPart -split ':', 2)[0].Trim()
                if ($exportName -match '^[A-Za-z_][A-Za-z0-9_]*$' -and -not $exportNameList.Contains($exportName)) {
                    $exportNameList.Add($exportName) | Out-Null
                }
            }
        }
    }

    return $exportNameList.ToArray()
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$distDirectoryPath = Join-Path $repoRoot "dist"
$bundleOutputPath = Join-Path $repoRoot $bundleRelativePath
$launcherOutputPath = Join-Path $repoRoot "true-aim.lua"

New-Item -ItemType Directory -Force -Path $distDirectoryPath | Out-Null

$segmentMetadataList = New-Object 'System.Collections.Generic.List[object]'
$totalExportCount = 0

foreach ($relativePath in $segmentPaths) {
    $absolutePath = Join-Path $repoRoot $relativePath
    if (-not (Test-Path -LiteralPath $absolutePath)) {
        throw "Missing source segment: $relativePath"
    }

    $normalizedRelativePath = $relativePath -replace "\\", "/"
    $sourceText = [System.IO.File]::ReadAllText($absolutePath)
    $exportNames = @(Get-TopLevelLocalExportNames $sourceText)
    $totalExportCount += $exportNames.Count

    $segmentMetadataList.Add([pscustomobject]@{
        RelativePath = $normalizedRelativePath
        SourceText = $sourceText
        ExportNames = $exportNames
    }) | Out-Null
}

$bundleBuilder = New-Object System.Text.StringBuilder
Add-BundleLine $bundleBuilder "-- true-aim bundle: generated by scripts/build.ps1"
Add-BundleLine $bundleBuilder ('-- repository: ' + $repositoryFullName + ' @ ' + $branchName)
Add-BundleLine $bundleBuilder "local LoadStringFunction = loadstring or load"
Add-BundleLine $bundleBuilder 'if type(LoadStringFunction) ~= "function" then'
Add-BundleLine $bundleBuilder '	error("true-aim: loadstring is unavailable in this environment", 0)'
Add-BundleLine $bundleBuilder "end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "local function ResolveExecutionEnvironmentTable()"
Add-BundleLine $bundleBuilder '	if type(getfenv) == "function" then'
Add-BundleLine $bundleBuilder '		local SuccessBoolean, ResultValue = pcall(getfenv, 0)'
Add-BundleLine $bundleBuilder '		if SuccessBoolean and type(ResultValue) == "table" then'
Add-BundleLine $bundleBuilder "			return ResultValue"
Add-BundleLine $bundleBuilder "		end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder '		SuccessBoolean, ResultValue = pcall(getfenv)'
Add-BundleLine $bundleBuilder '		if SuccessBoolean and type(ResultValue) == "table" then'
Add-BundleLine $bundleBuilder "			return ResultValue"
Add-BundleLine $bundleBuilder "		end"
Add-BundleLine $bundleBuilder "	end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "	return _G"
Add-BundleLine $bundleBuilder "end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "local SharedEnvironmentTable = ResolveExecutionEnvironmentTable()"
Add-BundleLine $bundleBuilder 'if type(SharedEnvironmentTable) ~= "table" then'
Add-BundleLine $bundleBuilder '	error("true-aim: failed to resolve execution environment", 0)'
Add-BundleLine $bundleBuilder "end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder 'SharedEnvironmentTable.__TRUE_AIM_EXPORT_ENV = SharedEnvironmentTable'
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "local BundleSegmentsTable = {"

foreach ($segmentMetadata in $segmentMetadataList) {
    Add-BundleLine $bundleBuilder "	{"
    Add-BundleLine $bundleBuilder ('		path = ' + (ConvertTo-LuaQuotedStringLiteral $segmentMetadata.RelativePath) + ",")
    Add-BundleLine $bundleBuilder "		exports = {"
    foreach ($exportName in $segmentMetadata.ExportNames) {
        Add-BundleLine $bundleBuilder ('			' + (ConvertTo-LuaQuotedStringLiteral $exportName) + ",")
    }
    Add-BundleLine $bundleBuilder "		},"
    Add-BundleLine $bundleBuilder ('		source = ' + (ConvertTo-LuaLongStringLiteral $segmentMetadata.SourceText) + ",")
    Add-BundleLine $bundleBuilder "	},"
}

Add-BundleLine $bundleBuilder "}"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "local function CompileSourceString(SourceString, ChunkNameString)"
Add-BundleLine $bundleBuilder '	if LoadStringFunction == load and type(load) == "function" then'
Add-BundleLine $bundleBuilder '		return LoadStringFunction(SourceString, ChunkNameString, "t", SharedEnvironmentTable)'
Add-BundleLine $bundleBuilder "	end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "	local ChunkFunction, CompileErrorString = LoadStringFunction(SourceString, ChunkNameString)"
Add-BundleLine $bundleBuilder '	if type(ChunkFunction) == "function" and type(setfenv) == "function" then'
Add-BundleLine $bundleBuilder '		pcall(setfenv, ChunkFunction, SharedEnvironmentTable)'
Add-BundleLine $bundleBuilder "	end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "	return ChunkFunction, CompileErrorString"
Add-BundleLine $bundleBuilder "end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "local function CompileAndRunSegment(SegmentTable)"
Add-BundleLine $bundleBuilder "	local WrappedSourceString = SegmentTable.source"
Add-BundleLine $bundleBuilder "	if #SegmentTable.exports > 0 then"
Add-BundleLine $bundleBuilder "		local ExportLinesTable = {}"
Add-BundleLine $bundleBuilder "		for IndexNumber, ExportNameString in ipairs(SegmentTable.exports) do"
Add-BundleLine $bundleBuilder '			ExportLinesTable[IndexNumber] = ("__TRUE_AIM_EXPORT_ENV[%q] = %s"):format(ExportNameString, ExportNameString)'
Add-BundleLine $bundleBuilder "		end"
Add-BundleLine $bundleBuilder '		WrappedSourceString = WrappedSourceString .. "\n" .. table.concat(ExportLinesTable, "\n")'
Add-BundleLine $bundleBuilder "	end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder '	local ChunkFunction, CompileErrorString = CompileSourceString(WrappedSourceString, "@" .. SegmentTable.path)'
Add-BundleLine $bundleBuilder '	if type(ChunkFunction) ~= "function" then'
Add-BundleLine $bundleBuilder '		error(("true-aim: failed to compile segment %s (%s)"):format(SegmentTable.path, tostring(CompileErrorString)), 0)'
Add-BundleLine $bundleBuilder "	end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "	local SuccessBoolean, ResultValue = pcall(ChunkFunction)"
Add-BundleLine $bundleBuilder '	if not SuccessBoolean then'
Add-BundleLine $bundleBuilder '		error(ResultValue, 0)'
Add-BundleLine $bundleBuilder "	end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "	return ResultValue"
Add-BundleLine $bundleBuilder "end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "for _, SegmentTable in ipairs(BundleSegmentsTable) do"
Add-BundleLine $bundleBuilder "	CompileAndRunSegment(SegmentTable)"
Add-BundleLine $bundleBuilder "end"
Add-BundleLine $bundleBuilder ""
Add-BundleLine $bundleBuilder "SharedEnvironmentTable.__TRUE_AIM_EXPORT_ENV = nil"

[System.IO.File]::WriteAllText($bundleOutputPath, $bundleBuilder.ToString(), $utf8NoBom)

$launcherBuilder = New-Object System.Text.StringBuilder
Add-BundleLine $launcherBuilder "local LoadStringFunction = loadstring or load"
Add-BundleLine $launcherBuilder 'if type(LoadStringFunction) ~= "function" then'
Add-BundleLine $launcherBuilder '	error("true-aim: loadstring is unavailable in this environment", 0)'
Add-BundleLine $launcherBuilder "end"
Add-BundleLine $launcherBuilder ""
Add-BundleLine $launcherBuilder ('local RepositoryFullNameString = ' + (ConvertTo-LuaQuotedStringLiteral $repositoryFullName))
Add-BundleLine $launcherBuilder ('local BranchNameString = ' + (ConvertTo-LuaQuotedStringLiteral $branchName))
Add-BundleLine $launcherBuilder ('local BundleRelativePathString = ' + (ConvertTo-LuaQuotedStringLiteral ($bundleRelativePath -replace "\\", "/")))
Add-BundleLine $launcherBuilder 'local CacheBustString = tostring(os.clock()):gsub("%.", "")'
Add-BundleLine $launcherBuilder 'local RawUrlString = ("https://raw.githubusercontent.com/%s/%s/%s"):format('
Add-BundleLine $launcherBuilder "	RepositoryFullNameString,"
Add-BundleLine $launcherBuilder "	BranchNameString,"
Add-BundleLine $launcherBuilder "	BundleRelativePathString"
Add-BundleLine $launcherBuilder ")"
Add-BundleLine $launcherBuilder 'local SuccessBoolean, ResultValue = pcall(game.HttpGet, game, RawUrlString .. "?v=" .. CacheBustString)'
Add-BundleLine $launcherBuilder "if not SuccessBoolean then"
Add-BundleLine $launcherBuilder '	error(("true-aim: failed to fetch bundle (%s)"):format(tostring(ResultValue)), 0)'
Add-BundleLine $launcherBuilder "end"
Add-BundleLine $launcherBuilder ""
Add-BundleLine $launcherBuilder 'local ChunkFunction, CompileErrorString = LoadStringFunction(ResultValue, "@" .. BundleRelativePathString)'
Add-BundleLine $launcherBuilder 'if type(ChunkFunction) ~= "function" then'
Add-BundleLine $launcherBuilder '	error(("true-aim: failed to compile bundle (%s)"):format(tostring(CompileErrorString)), 0)'
Add-BundleLine $launcherBuilder "end"
Add-BundleLine $launcherBuilder ""
Add-BundleLine $launcherBuilder "return ChunkFunction()"

[System.IO.File]::WriteAllText($launcherOutputPath, $launcherBuilder.ToString(), $utf8NoBom)

Write-Host ("Built {0} and {1} from {2} source segments with {3} exported top-level locals." -f $bundleOutputPath, $launcherOutputPath, $segmentPaths.Count, $totalExportCount)
